### PR TITLE
changed function call tf.nn.deconv2d to tf.nn.conv2d_transpose for TensorFlow 0.7.0

### PR DESCRIPTION
**Pull request by terrybroad**
I have changed function call `tf.nn.deconv2d` in ops.py to `tf.nn.conv2d_transpose` to reflect the name change in TensorFlow 0.7.0.

### CODE REVIEW

**Comment by carpedm20** [comment]
thanks for commit but we'd better use both of them for legacy. What about change the line from

    deconv = tf.nn.conv2d_transpose(input_, w, output_shape=output_shape,

to

    try:
        deconv = tf.nn.conv2d_transpose(
    catch:
        deconv = tf.nn.deconv2d(

**Comment by terrybroad** [comment]
Yes, that is a much better idea. Do you want me to send another pull request or do you want to just do it yourself?

**Comment by carpedm20** [comment]
@terrybroad If you make another commit then I'll merge it. You don't need to make another pull request and just commit in this branch and push it :+1:

**Comment by terrybroad** [comment]
Ok I have fixed that now with:

`         try:
             deconv = tf.nn.conv2d_transpose(input_, w, output_shape=output_shape,
                                 strides=[1, d_h, d_w, 1])
 
         # Support for verisons of TensorFlow before 0.7.0
         except AttributeError:
             deconv = tf.nn.deconv2d(input_, w, output_shape=output_shape,
                                  strides=[1, d_h, d_w, 1]) `

**Pull request merged**
